name: Build

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    uses: your-org/your-central-repo/.github/workflows/reusable-workflow.yml@main
    with:
      working-folder: ${{ vars.AgentWorkingFolder }}
      scripts-folder: ${{ vars.AgentWorkingFolder }}/pipeline/scripts
