name: Fetch and Store GitHub Data for Organization

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  fetch-and-store:
    runs-on: self-hosted

    steps:
      # 1. Ensure Python is installed
      - name: Install Python if not present
        run: |
          if (!(Get-Command python -ErrorAction SilentlyContinue)) {
            Write-Host "Python not found. Installing Python..."
            $pythonInstallerUrl = "https://www.python.org/ftp/python/3.9.13/python-3.9.13-amd64.exe"
            $installerPath = "$env:USERPROFILE\\python-installer.exe"
            Invoke-WebRequest -Uri $pythonInstallerUrl -OutFile $installerPath
            Start-Process -FilePath $installerPath -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1" -NoNewWindow -Wait
            Remove-Item $installerPath
          } else {
            Write-Host "Python is already installed. Version: $(python --version)"
          }
        shell: powershell

      # 2. Verify Python installation
      - name: Verify Python Installation
        run: |
          python --version
          pip --version
        shell: powershell

      # 3. Install dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests mysql-connector-python

      # 4. Run the Python script to fetch and store data
      - name: Fetch and Store Data in MySQL
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}  # Use the PAT instead of the default GITHUB_TOKEN
          ORG_NAME: ni
          REQUIRED_TOPIC: ni-open-source
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: root
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ni_open_source_github_data
        run: python .github/scripts/fetch_store_org_data_conditional.py
