name: Troubleshoot agent

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Build LabVIEW
    runs-on: windows-latest
    env:
      RELATIVE_PATH: ${{ vars.AgentWorkingFolder }}
      SCRIPTS_PATH: ${{ vars.AgentWorkingFolder }}\pipeline\scripts

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1.0.0

    - name: Set agent into development mode
      shell: powershell
      working-directory: ${{ env.SCRIPTS_PATH }}
      run: |
        & ".\Set_Development_Mode.ps1" -RelativePath "${{ env.RELATIVE_PATH }}"
