name: PR Triggered Tests

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  trigger-azure-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check if authorized to run tests
        id: check
        run: |
          echo "ok=true" >> $GITHUB_OUTPUT

      - name: Trigger Azure DevOps Pipeline
        if: steps.check.outputs.ok == 'true'
        uses: Azure/pipelines@v1.2
        with:
          azure_devops_organization_url: 'https://dev.azure.com/sergiovelderrain'
          project_name: 'sergiovelderrain'
          definition_id: '3'
          parameters: |
            resources:
              repositories:
                self:
                  refName: "refs/heads/${{ github.event_name == 'workflow_dispatch' && 'develop' || github.event.pull_request.head.ref }}"
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
