      - name: Poll pipeline status until completion
        id: poll-status
        env:
          ORGANIZATION: sergiovelderrain
          PROJECT_NAME: sergiovelderrain
          DEBUG_MODE: ${{ env.DEBUG_MODE }}
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          set -euo pipefail
          if [ "$DEBUG_MODE" = "true" ]; then
            echo "::debug::Debug mode enabled for polling."
          fi

          if [ -z "${AZURE_DEVOPS_PAT}" ]; then
            echo "Error: AZURE_DEVOPS_PAT not set." >&2
            exit 1
          fi

          if [ -z "${BUILD_ID:-}" ]; then
            echo "Error: BUILD_ID not set." >&2
            exit 1
          fi

          AUTH_HEADER=$(printf ":%s" "${AZURE_DEVOPS_PAT}" | base64 -w 0)
          STATUS_URL="https://dev.azure.com/${ORGANIZATION}/${PROJECT_NAME}/_apis/build/builds/${BUILD_ID}?api-version=6.0"
          TIMELINE_URL="https://dev.azure.com/${ORGANIZATION}/${PROJECT_NAME}/_apis/build/builds/${BUILD_ID}/timeline?api-version=6.0"

          MAX_ATTEMPTS=30
          SLEEP_SECONDS=10
          ATTEMPT=1

          while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
            if [ "$DEBUG_MODE" = "true" ]; then
              echo "::debug::Attempt $ATTEMPT of $MAX_ATTEMPTS"
            fi

            rm -f status.json || true
            if ! wget --quiet --header="Authorization: Basic ${AUTH_HEADER}" -O status.json "$STATUS_URL"; then
              echo "Error: Failed to fetch build status." >&2
              exit 1
            fi

            if [ "$DEBUG_MODE" = "true" ]; then
              echo "::debug::Pipeline status response:"
              cat status.json | jq .
            fi

            STATUS=$(jq -r '.status // empty' status.json)
            RESULT=$(jq -r '.result // empty' status.json)

            if [ -z "$STATUS" ]; then
              echo "Error: Status not found in pipeline response." >&2
              if [ "$DEBUG_MODE" = "true" ]; then
                echo "::debug::Parsed response:"
                cat status.json
              fi
              exit 1
            fi

            echo "Current Status: $STATUS"
            if [ "$DEBUG_MODE" = "true" ]; then
              echo "::debug::Current Result: $RESULT"
            fi

            # Fetch and report timeline for more detailed feedback
            rm -f timeline.json || true
            if ! wget --quiet --header="Authorization: Basic ${AUTH_HEADER}" -O timeline.json "$TIMELINE_URL"; then
              echo "Error: Failed to fetch timeline." >&2
              exit 1
            fi

            # Print detailed timeline feedback
            echo "---- Pipeline Detailed Timeline ----"
            cat timeline.json | jq '.records[] | {Type: .type, Name: .name, State: .state, Result: .result, StartTime: .startTime, FinishTime: .finishTime, Issues: .issues}'
            echo "-----------------------------------"

            if [ "$STATUS" = "completed" ]; then
              # If completed, check the final result
              break
            fi

            sleep $SLEEP_SECONDS
            ATTEMPT=$((ATTEMPT+1))
          done

          if [ "$STATUS" != "completed" ]; then
            echo "Error: Build not completed within the timeout." >&2
            exit 1
          fi

          if [ "$RESULT" != "succeeded" ]; then
            echo "Error: Build completed but did not succeed. Result: $RESULT" >&2
            exit 1
          fi

          echo "Build succeeded!"