name: PR Triggered Tests

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  trigger-azure-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check if authorized to run tests
        id: check
        run: |
          echo "ok=true" >> $GITHUB_OUTPUT

      - name: Trigger Azure DevOps Pipeline
        if: steps.check.outputs.ok == 'true'
        uses: Azure/pipelines@v1.2
        with:
          azure-devops-project-url: 'https://dev.azure.com/sergiovelderrain/sergiovelderrain'
          azure-pipeline-name: 'ni.labview-icon-editor-test'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_PAT }}
